---
title: "Class 9"
format: html
---
Q1. How many different candy types are in this dataset? --9
Q2. How many fruity candy types are in the dataset? --38
```{R}
url <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/candy-power-ranking/candy-data.csv"

candy = read.csv(url, row.names=1)
head(candy)
sum(candy$fruity==1)
```

Q3. What is your favorite candy in the dataset and what is it’s winpercent value? --Twix, 81.64291
Q4. What is the winpercent value for “Kit Kat”? --76.7686
Q5. What is the winpercent value for “Tootsie Roll Snack Bars”? --49.6535	
```{R}
candy["Kit Kat",]$winpercent
library(dplyr)
candy |> 
  filter(rownames(candy)=="Tootsie Roll Snack Bars") |> 
  select(winpercent)
```

The `%in%` is useful for checking the intersection of two vectors 
```{R}
#do elements in c1 exist in c2
c("barry", "liz", "chandra") %in% c("paul", "alice", "liz")
```
```{R}
#select based on multiple conditions
candy |>
  filter(winpercent > 75)|>
  filter(pricepercent < 0.5)
```

Q6. Is there any variable/column that looks to be on a different scale to the majority of the other columns in the dataset? --winpercent
Q7. What do you think a zero and one represent for the candy$chocolate column? --"0" means non-chocolate, "1" means containing chocolate
```{R}
library(skimr)
skim(candy)
skim(scale(candy))
```

Q8. Plot a histogram of winpercent values
Q9. Is the distribution of winpercent values symmetrical? --no, right skewed
Q10. Is the center of the distribution above or below 50%? --median is below 50%
```{R}
hist(candy$winpercent)

#center as median
abline(v=median(candy$winpercent), col="red")
#center as mean
abline(v=mean(candy$winpercent), col="blue")
summary(candy$winpercent)
```
Q11. On average is chocolate candy higher or lower ranked than fruit candy? --Chocolate
Q12. Is this difference statistically significant? -Yes
```{R}
inds<-as.logical(candy$chocolate)
cho.win <- candy[inds,]$winpercent

fru.win <- candy |> 
  filter(fruity==1) |>
  select(winpercent)

summary(cho.win)
summary(fru.win)
t.test(cho.win, fru.win)
```

Q13. What are the five least liked candy types in this set?
Q14. What are the top 5 all time favorite candy types out of this set?
```{R}
candy %>% arrange(winpercent) %>% head(5)
candy %>% arrange(winpercent, ) %>% tail(5)
```

Q15. Make a first barplot of candy ranking based on winpercent values.
```{R}
library(ggplot2)

ggplot(candy) + 
  aes(winpercent, rownames(candy)) +
  geom_col()
```
Q16. This is quite ugly, use the reorder() function to get the bars sorted by winpercent?
Q17. What is the worst ranked chocolate candy? --Sixlets
Q18. What is the best ranked fruity candy? --Starburst
Q. color code my favorite Twix in blue
```{R}
#order sorts the index of element from original list; it doesn't change the original list
n <- c("d", "a")
order(n)
n[order(n)]


#sort returns the sorted value of element but doesn't change the original list either
s <- c(5,2,7,4)
sort(s)
s

my_cols=rep("black", nrow(candy))
my_cols[as.logical(candy$bar)] = "brown"
my_cols[as.logical(candy$fruity)] = "red"
my_cols[as.logical(candy$chocolate)] = "chocolate"
my_cols[rownames(candy)=="Twix"] = "blue"
my_cols

ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy),winpercent)) +
  geom_col(fill=my_cols) + 
  theme(axis.text.y = element_text(size = 5))
```

Q19. Which candy type is the highest ranked in terms of winpercent for the least money - i.e. offers the most bang for your buck? --Reese's Peanut Butter cup
Q20. What are the top 5 most expensive candy types in the dataset and of these which is the least popular? --Nik L Nip
```{R}
library(ggrepel)

ggplot(candy) +
  aes(winpercent, pricepercent, label=rownames(candy)) +
  geom_point(col=my_cols) + 
  geom_text_repel(col=my_cols, size=3)
```
#### Exploring the correlation structure
```{R}
library(corrplot)
cij <- cor(candy)
corrplot(cij)
```

Q22. Examining this plot what two variables are anti-correlated (i.e. have minus values)? --Chocolate and Fruity
Q23. Similarly, what two variables are most positively correlated? --Chocolate & winprecent, or chocolate & bar

#### PCA
```{R}
pca <- prcomp(candy, scale=TRUE)
summary(pca)

plot(pca$x[,1], pca$x[,2], col=my_cols, pch=16)
```

Load variables
Q24. What original variables are picked up strongly by PC1 in the positive direction? Do these make sense to you? --Fruity, hard, pluribus; these three have positive correlation
```{R}
#PC1
pca$rotation[,1]
par(mar=c(8,4,2,2))
barplot(pca$rotation[,1], las=2, ylab="PC1 Contribution")

ggplot(pca$rotation, aes(rownames(pca$rotation), PC1)) + geom_col() + 
  labs(x="PC1") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```


